const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");

module.exports = async function generateCv(data) {
  const roleFolder = "cv";
  const baseDir = process.env.PDF_STORAGE_PATH || path.join(__dirname, "..", "..", "data");
  const userFolder = data.username || "guest";
  const dataDir = path.join(baseDir, roleFolder, userFolder);
  if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

  const outPath = path.join(dataDir, `cv_${Date.now()}.pdf`);
  const doc = new PDFDocument({ size: "A4", margin: 50 });

  doc.pipe(fs.createWriteStream(outPath));

  // HEADER: Name as logo
  doc
    .fillColor("#1F2937")
    .fontSize(32)
    .font("Helvetica-Bold")
    .text(data.name || "Unnamed", { align: "center" })
    .moveDown(0.2);

  // Contact Info
  const contactInfo = [data.email, data.github, data.phone].filter(Boolean).join(" • ");
  doc
    .fontSize(11)
    .font("Helvetica")
    .fillColor("#374151")
    .text(contactInfo, { align: "center" })
    .moveDown(0.5);

  // Divider
  doc
    .strokeColor("#D1D5DB")
    .lineWidth(1)
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .stroke();

  doc.moveDown(1);

  // PROFILE
  if (data.bio) {
    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .fillColor("#111827")
      .text("Profile", { underline: true });
    doc.moveDown(0.2);
    doc
      .fontSize(11)
      .font("Helvetica")
      .fillColor("#374151")
      .text(data.bio, { align: "justify" });
    doc.moveDown(0.5);
  }

  // SKILLS
  if (data.skills?.length) {
    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .fillColor("#111827")
      .text("Skills", { underline: true });
    doc.moveDown(0.2);
    doc
      .fontSize(11)
      .font("Helvetica")
      .fillColor("#374151")
      .text(data.skills.join(", "));
    doc.moveDown(0.5);
  }

  // PROJECTS
  if (data.projects?.length) {
    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .fillColor("#111827")
      .text("Projects", { underline: true });
    doc.moveDown(0.2);
    data.projects.forEach((proj, i) =>
      doc
        .fontSize(11)
        .font("Helvetica")
        .fillColor("#374151")
        .text(`${i + 1}. ${proj}`, { align: "left" })
    );
    doc.moveDown(0.5);
  }

  // FOOTER
  doc
    .moveDown(2)
    .fontSize(10)
    .fillColor("#9CA3AF")
    .text("Generated by Ryan O Cv", { align: "center" });

  doc.end();

  return path.join("data", roleFolder, userFolder, path.basename(outPath));
};
