const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

module.exports = async function generateProfessional(data) {
  const roleFolder = "professional";
  const baseDir = process.env.PDF_STORAGE_PATH || path.join(__dirname, "..", "..", "data");
  const userFolder = data.username || "guest";
  const dataDir = path.join(baseDir, roleFolder, userFolder);

  if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

  const outPath = path.join(dataDir, `p_${Date.now()}.pdf`);
  const doc = new PDFDocument({ size: "A4", margin: 50 });

  doc.pipe(fs.createWriteStream(outPath));

  // HEADER
  doc
    .fillColor("#1F2937") // dark slate
    .fontSize(26)
    .font("Helvetica-Bold")
    .text("Professional Portfolio", { align: "center" })
    .moveDown(0.5);

  doc
    .strokeColor("#D1D5DB") // light gray line
    .lineWidth(1)
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .stroke();

  doc.moveDown(1);

  // PERSONAL INFO
  doc
    .fontSize(14)
    .font("Helvetica-Bold")
    .fillColor("#111827")
    .text("Personal Information", { underline: true });

  doc.moveDown(0.3);
  doc
    .font("Helvetica")
    .fillColor("#374151")
    .text(`Name: ${data.name || "N/A"}`)
    .text(`Email: ${data.email || "N/A"}`)
    .text(`Phone: ${data.phone || "N/A"}`)
    .moveDown(0.5);

  // BIO
  if (data.bio) {
    doc
      .font("Helvetica-Bold")
      .fillColor("#111827")
      .text("Bio", { underline: true });
    doc.moveDown(0.3);
    doc
      .font("Helvetica")
      .fillColor("#374151")
      .text(data.bio, { align: "justify" })
      .moveDown(0.5);
  }

  // SKILLS
  if (data.skills && data.skills.length) {
    doc
      .font("Helvetica-Bold")
      .fillColor("#111827")
      .text("Skills", { underline: true });
    doc.moveDown(0.3);
    doc
      .font("Helvetica")
      .fillColor("#374151")
      .text(data.skills.join(", "), { align: "left" })
      .moveDown(0.5);
  }

  // EXPERIENCE
  if (data.experience && data.experience.length) {
    doc
      .font("Helvetica-Bold")
      .fillColor("#111827")
      .text("Experience", { underline: true });
    doc.moveDown(0.3);
    data.experience.forEach((exp, idx) => {
      doc
        .font("Helvetica-Bold")
        .fillColor("#111827")
        .text(`${idx + 1}. ${exp.position || "N/A"} at ${exp.company || "N/A"}`, { continued: true })
        .font("Helvetica")
        .fillColor("#6B7280")
        .text(` (${exp.duration || "N/A"})`);
      if (exp.details) doc.text(`    - ${exp.details}`);
      doc.moveDown(0.3);
    });
    doc.moveDown(0.5);
  }

  // FOOTER
  doc
    .moveDown(2)
    .fontSize(10)
    .fillColor("#9CA3AF")
    .text("Generated by Ryan Offy Professional", { align: "center" });

  doc.end();

  return path.join("data", roleFolder, userFolder, path.basename(outPath));
};
